// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/connector"
	"go.opentelemetry.io/collector/connector/connectortest"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"
)

func NewSettings(tt *componenttest.Telemetry) connector.Settings {
	set := connectortest.NewNopSettings(connectortest.NopType)
	set.ID = component.NewID(component.MustNewType("logs_to_spans"))
	set.TelemetrySettings = tt.NewTelemetrySettings()
	return set
}

func AssertEqualConnectorLogsToSpansActiveGroups(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_connector_logs_to_spans_active_groups",
		Description: "Number of log groups currently buffered by the connector. [Development]",
		Unit:        "{group}",
		Data: metricdata.Gauge[int64]{
			DataPoints: dps,
		},
	}
	got, err := tt.GetMetric("otelcol_connector_logs_to_spans_active_groups")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualConnectorLogsToSpansGroupsEvicted(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_connector_logs_to_spans_groups_evicted",
		Description: "Number of groups flushed early because max_groups was reached. [Development]",
		Unit:        "{group}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_connector_logs_to_spans_groups_evicted")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualConnectorLogsToSpansLogsIngested(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_connector_logs_to_spans_logs_ingested",
		Description: "Number of log records consumed by the connector. [Development]",
		Unit:        "{log_record}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_connector_logs_to_spans_logs_ingested")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualConnectorLogsToSpansTracesCreated(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_connector_logs_to_spans_traces_created",
		Description: "Number of traces emitted by the connector. [Development]",
		Unit:        "{trace}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_connector_logs_to_spans_traces_created")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualConnectorLogsToSpansUnmatchedDropped(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_connector_logs_to_spans_unmatched_dropped",
		Description: "Number of log records dropped because no group_by_keys or group_by_attributes entry matched. [Development]",
		Unit:        "{log_record}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_connector_logs_to_spans_unmatched_dropped")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}
