// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/agardnerIT/logs-to-spans-otel")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/agardnerIT/logs-to-spans-otel")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                metric.Meter
	mu                                   sync.Mutex
	registrations                        []metric.Registration
	ConnectorLogsToSpansActiveGroups     metric.Int64ObservableGauge
	ConnectorLogsToSpansGroupsEvicted    metric.Int64Counter
	ConnectorLogsToSpansLogsIngested     metric.Int64Counter
	ConnectorLogsToSpansTracesCreated    metric.Int64Counter
	ConnectorLogsToSpansUnmatchedDropped metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterConnectorLogsToSpansActiveGroupsCallback sets callback for observable ConnectorLogsToSpansActiveGroups metric.
func (builder *TelemetryBuilder) RegisterConnectorLogsToSpansActiveGroupsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ConnectorLogsToSpansActiveGroups, obs: o})
		return nil
	}, builder.ConnectorLogsToSpansActiveGroups)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ConnectorLogsToSpansActiveGroups, err = builder.meter.Int64ObservableGauge(
		"otelcol_connector_logs_to_spans_active_groups",
		metric.WithDescription("Number of log groups currently buffered by the connector. [Development]"),
		metric.WithUnit("{group}"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorLogsToSpansGroupsEvicted, err = builder.meter.Int64Counter(
		"otelcol_connector_logs_to_spans_groups_evicted",
		metric.WithDescription("Number of groups flushed early because max_groups was reached. [Development]"),
		metric.WithUnit("{group}"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorLogsToSpansLogsIngested, err = builder.meter.Int64Counter(
		"otelcol_connector_logs_to_spans_logs_ingested",
		metric.WithDescription("Number of log records consumed by the connector. [Development]"),
		metric.WithUnit("{log_record}"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorLogsToSpansTracesCreated, err = builder.meter.Int64Counter(
		"otelcol_connector_logs_to_spans_traces_created",
		metric.WithDescription("Number of traces emitted by the connector. [Development]"),
		metric.WithUnit("{trace}"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorLogsToSpansUnmatchedDropped, err = builder.meter.Int64Counter(
		"otelcol_connector_logs_to_spans_unmatched_dropped",
		metric.WithDescription("Number of log records dropped because no group_by_keys or group_by_attributes entry matched. [Development]"),
		metric.WithUnit("{log_record}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
