// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the connector/logs_to_spans component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("logs_to_spans")
	ScopeName = "github.com/agardnerIT/logs-to-spans-otel"
)

const (
	LogsToTracesStability = component.StabilityLevelDevelopment
)
